### ISSUE TITLE
Request for a new section about APIs

### ISSUE THREAD

**Issue by reganto** [DjangoEx/python-engineer-roadmap#108]
Hi!

I'd like to add a section for APIs, but I'm not sure where to add this section. This is my suggestion:

* Advanced Topics:
    * API:
         - Guidlines and Best Practices
         - Bla Bla
         .
         .

What is your opinion?

Best Regards
Reganto

**Comment by lnxpy** [comment]
That's awesome. That section is def needed for sure. Thanks. Much appreciate that. Feel free to add that section btw. :))
