### ISSUE TITLE
DevOps section

### ISSUE THREAD

**Issue by amirpsd** [DjangoEx/python-engineer-roadmap#121]
Hi guys.
In my opinion [DevOps](https://github.com/DjangoEx/python-engineer-roadmap#devops) section is better not written in repo, because DevOps has a lot of content and clutters the repo. 
We can refer the DevOps section to another roadmap, like [this](https://roadmap.sh/devops) or [this](https://github.com/ahmadalibagheri/devops-roadmap).
thanks for your attention.

**Comment by bobycloud** [comment]
Hello, this is not a DevOps roadmap; rather, it is a collection of Python-DevOps materials. It is not smart to follow the DevOps roadmap here, and it is preferable to do so in the resource you have mentioned.
So, from the beginning to the end, we would have no DevOps roadmap! @amirpsd.
